# action.yml
name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
  github-token:
    description: 'GitHub token'
    required: false
runs:
  using: 'docker'
  image: 'docker://ghcr.io/gsmet/github-action-playground:main'
  #pre-entrypoint: '/work/application'
  #post-entrypoint: '/work/application'
