# action.yml
name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
  github-token:
    description: 'GitHub token'
    required: false
  maven-repository-read-token:
    description: 'Maven repository read token'
    required: true
runs:
  using: "composite"
  steps:
    - run: curl -Ls https://sh.jbang.dev | bash -s - app setup
      shell: bash
    - run: curl -v -L https://${{ inputs.maven-repository-read-token }}@maven.pkg.github.com/gsmet/github-action-playground/io/github/gsmet/github-action-playground/1.0.0-SNAPSHOT/github-action-playground-1.0.0-20220722.093742-12.pom
      shell: bash
    - run: ~/.jbang/bin/jbang --verbose --repos 'https://${{ inputs.maven-repository-read-token }}@maven.pkg.github.com/gsmet/github-action-playground/' --repos 'mavencentral' io.github.gsmet:github-action-playground:1.0.0-SNAPSHOT
      shell: bash
      env:
        JSON_INPUTS: ${{ toJSON(inputs) }}
