# action.yml
name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/gsmet/github-action-playground:main'
  pre-entrypoint: '/work/application'
  post-entrypoint: '/work/application'
  args:
    - ${{ inputs.who-to-greet }}
